---
project_name: aws-devops-lab
env_name: development

common_tags:
  project: "{{ project_name }}"
  environment: "{{ env_name }}"
  managed_by: ansible

ntp_servers:
  - pool.ntp.org

deploy_user: deploy
deploy_group: deploy
