---
win_iis_features:
  - Web-Server
  - Web-Mgmt-Console

win_iis_sites:
  - name: Default Web Site
    port: 80
    physical_path: C:\inetpub\wwwroot
    state: started
  - name: staging
    port: 8080
    physical_path: C:\inetpub\staging
    state: started

win_iis_app_pool_name: DefaultAppPool
